"use client";
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Home;
const jsx_runtime_1 = require("react/jsx-runtime");
const Section_1 = __importDefault(require("../components/Section"));
const DemoShortener_1 = __importDefault(require("../components/DemoShortener"));
const FeatureCard_1 = __importDefault(require("../components/FeatureCard"));
const fa_1 = require("react-icons/fa");
function Home() {
    return ((0, jsx_runtime_1.jsxs)("main", { children: [(0, jsx_runtime_1.jsxs)(Section_1.default, { children: [(0, jsx_runtime_1.jsx)("h1", { className: "text-5xl font-bold neon mb-6 text-center", children: "Shorten, Brand & Track Your Links" }), (0, jsx_runtime_1.jsx)("p", { className: "text-lg text-center mb-8 max-w-2xl mx-auto", children: "NeonShort is the modern, secure, and scalable URL shortener for individuals, teams, and businesses. Create branded links, track analytics, and grow your audience with confidence." }), (0, jsx_runtime_1.jsx)(DemoShortener_1.default, {})] }), (0, jsx_runtime_1.jsxs)(Section_1.default, { title: "Why NeonShort?", className: "flex flex-wrap justify-center gap-6", children: [(0, jsx_runtime_1.jsx)(FeatureCard_1.default, { icon: (0, jsx_runtime_1.jsx)(fa_1.FaLink, {}), title: "Branded Links", description: "Create custom, memorable short links for your brand or business." }), (0, jsx_runtime_1.jsx)(FeatureCard_1.default, { icon: (0, jsx_runtime_1.jsx)(fa_1.FaChartBar, {}), title: "Analytics", description: "Track clicks, referrers, locations, and device analytics in real time." }), (0, jsx_runtime_1.jsx)(FeatureCard_1.default, { icon: (0, jsx_runtime_1.jsx)(fa_1.FaQrcode, {}), title: "QR Codes", description: "Generate QR codes for every link, perfect for print and offline sharing." }), (0, jsx_runtime_1.jsx)(FeatureCard_1.default, { icon: (0, jsx_runtime_1.jsx)(fa_1.FaUserFriends, {}), title: "Team Collaboration", description: "Invite team members, manage roles, and collaborate on link campaigns." }), (0, jsx_runtime_1.jsx)(FeatureCard_1.default, { icon: (0, jsx_runtime_1.jsx)(fa_1.FaShieldAlt, {}), title: "Security & Privacy", description: "Industry-leading security, privacy controls, and GDPR compliance." }), (0, jsx_runtime_1.jsx)(FeatureCard_1.default, { icon: (0, jsx_runtime_1.jsx)(fa_1.FaCogs, {}), title: "Custom Domains", description: "Use your own domain for fully branded, trusted links." })] }), (0, jsx_runtime_1.jsx)(Section_1.default, { title: "How It Works", children: (0, jsx_runtime_1.jsxs)("ol", { className: "list-decimal list-inside text-lg max-w-2xl mx-auto space-y-2", children: [(0, jsx_runtime_1.jsxs)("li", { children: ["Paste your long URL above and click ", (0, jsx_runtime_1.jsx)("b", { children: "Shorten URL" }), "."] }), (0, jsx_runtime_1.jsx)("li", { children: "Sign up for a free account to manage, brand, and track your links." }), (0, jsx_runtime_1.jsx)("li", { children: "Access analytics, QR codes, and advanced features from your dashboard." })] }) }), (0, jsx_runtime_1.jsx)(Section_1.default, { title: "Get Started Today!", className: "text-center", children: (0, jsx_runtime_1.jsx)("a", { href: "/signup", className: "inline-block bg-gradient-to-r from-purple-500 to-blue-500 neon px-8 py-4 rounded text-white text-xl font-bold mt-4", children: "Sign Up Free" }) })] }));
}
//# sourceMappingURL=page.js.map